swagger: '2.0'
info:
  title: Hrnet employee API
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: hrnetbackend.test
basePath: /api/v1
schemes:
  - http
paths:
  /employee:
    post:
      tags:
        - User Module
      summary: Login
      description: API add an employee
      parameters:
        - in: body
          name: body
          description: Employee status
          required: true
          schema:
            $ref: '#/definitions/newEmployee'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/Employee'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    get:
      tags:
        - Get list of employee
      summary: Send the all list of employee
      description: API for get list of employee
      produces:
        - application/json
      responses:
        '200':
          description: List send succesfully
          schema:
            $ref: '#/definitions/ApiListEmployee'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorize
        '403':
          description: Forbidden
        '404':
          description: Transactions not found
        '500':
          description: Internal Server Error
  
definitions:
  newEmployee:
    properties:
      firstname:
        type: string
        description: user first name
      lastname:
        type: string
        description: user password
      dateBirthday:
        type: string
        description: date of birthday
      dateStart:
        type: string
        description: begin to work for us
      departement:
        type: string
        description: departement
      street:
        type: string
        description: street
      city:
        type: string
        description: city
      state:
        type: string
        description: state
      zipCode:
        type: integer
        description: Zip Code
  Employee:
    properties:
      id:
        type: integer
        description: user id
      firstname:
        type: string
        description: user first name
      lastname:
        type: string
        description: user password
      dateBirthday:
        type: string
        description: date of birthday
      dateStart:
        type: string
        description: begin to work for us
      departement:
        type: string
        description: departement
      street:
        type: string
        description: street
      city:
        type: string
        description: city
      state:
        type: string
        description: state
      zipCode:
        type: integer
        description: Zip Code
  ApiListEmployee:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Employee'